#!/bin/bash

# Install apache
#yum -y install httpd-2.4.41

# Set file and folder permissions
chown -R ec2-user:apache /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;

# If not done earlier
# sed -i "s|AllowOverride None|AllowOverride All|g"  /etc/httpd/conf/httpd.conf
# sed -i "s|index.html|index.php|g" /etc/httpd/conf/httpd.conf
# sed -i "s|Listen 80|Listen 0.0.0.0:80|g" /etc/httpd/conf/httpd.conf



